### ISSUE TITLE
🔧 Site: Add site TITLE & META info. (SEO needs)

### ISSUE THREAD

**Issue by u-u-z** [Limit-IM/limit-site#2]
- [x] Add title, meta info support dynamic routing support
- [x] `meta` name `name="twitter:*"` supports
- [x] `meta` property `property="og:*"` supports
- [x] favicons

## Assets need request.
- [x] favicons `32x32`, `16x16`

**Comment by George-Miao** [comment]
I would recommend using `next-seo` and `next-sitemap` as I have used them in my site before

**Comment by LemonHX** [comment]
https://twitter.com/limit_lab

**Comment by LemonHX** [comment]
track
